# JUEGO HISTORIA LOCA

print("CREA TU HISTORIA LOCA")
print("Ingresa las palabras que te solicitamos:\n")
# Declaramos las variables
# Con input para ingresarlo por consola

pal1 = input("Parte del cuerpo en plural: ")
pal2 = input("Adjetivo M en plural: ")
pal3 = input("Adjetivo M: ")
pal4 = input("Adjetivo M: ")
pal5 = input("Lugar: ")
pal6 = input("Animal: ")
pal7 = input("Parte del cuerpo: ")
pal8 = input("Adjetivo: ")
pal9 = input("Adjetivo F plural: ")
pal10 = input("Adverbio: ")
pal11 = input("Interjección: ")
pal12 = input("Adjetivo F plural: ")
pal13 = input("Nombre propio: ")
pal14 = input("Nombre F: ")

print("\nESTA ES LA HISTORIA QUE HAS CREADO:")
# Imprimimos la historia por pantalla
print(f"Antiguamente, el ser humano caminaba a cuatro {pal1.lower()},")
print(f"se expresaba mediante gruñidos {pal2.lower()} y no sabía encender")
print(f"un {pal3.lower()} fuego. Esta es la historia del día en que la humanidad")
print(f"cambió para siempre (traducida del {pal4.lower()} idioma de las cavernas):")
print("Hombre de las cavernas 1: En esta cueva hace más frío que en (el/la)")
print(f"{pal5.capitalize()}. Incluso con la piel del/de la {pal6.capitalize()} más caliente no")
print(f"consigo que mi {pal7.lower()} deje de tiritar.")
print("Hombre de las cavernas 2: Si al menos pudiésemos encontrar una")
print(f"manera de que el frío fuera más {pal8.lower()}.")
print("Hombre de las cavernas 1: Estoy aburrido. Creo que voy a jugar un")
print(f"rato con estas ramas {pal9.lower()}.")
print(f"Hombre de las cavernas 2: ¿Porqué no las frotas {pal10.lower()} a ver")
print("qué pasa?")
print(f"Hombre de las cavernas 1: ¡{pal11.capitalize()}! Está saliendo humo de ")
print(f"las {pal12.lower()} ramas!")
print("Hombre de las cavernas 2: ¡Ay! ¡Está caliente! ¡Por el amor de")
print(f"{pal13.capitalize()}, hemos conseguido calor!")
print("Hombre de las cavernas 1: A partir de ahora, llamaremos <fuego> a esta")
print(f"{pal14.capitalize()} mágica.")
